OPENAI_API_KEY = "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"

[connections.snowpark]
user=  "SHUBHAM68"
password= "Shubham123"
account= "nvalrcb-rh61158"
warehouse= "COMPUTE_WH"
database= "FINANCEDWH"
schema= "FDWH"